version: '3'
services:
    match:
        build: .
        restart: on-failure
        depends_on:
            - redis-db
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
            - REDIS_URL=redis://:@redis-db:6379/4
    redis-db:
        image: redis:3.2.8
        ports:
            - 6379:6379
