name: automatization

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  Continuos-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prepare nodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Test
        run: yarn test

  Continuos-Delivery:
    needs: Continuos-Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - run: echo ${{ secrets.HEROKU_API_KEY }}
      - run: echo ${{ secrets.HEROKU_APP_NAME_MATCH_DEVELOPMENT }}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_MATCH_DEVELOPMENT }}
          heroku_email: "anthony.bravo.berrio@gmail.com"
          branch: master
    if: ${{ github.event_name == 'pull_request' }}

  Continuos-Deployment:
    needs: Continuos-Integration
    runs-on: ubuntu-latest
    steps:
      - run: echo Continuos-Deployment
    if: ${{ github.event_name == 'push' }}
